# -*- coding: utf-8 -*-
"""FP_Ogedengbe_Osemudia_Sofa_Manufacturing_Assistance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0DnkT4tdp4nwXJaYg7LbzXJV8Zlp6A0
"""

import kagglehub

# Download latest version
fabric_path = kagglehub.dataset_download("priemshpathirana/fabric-stain-dataset")
frame_path = kagglehub.dataset_download("nomihsa965/large-scale-image-dataset-of-wood-surface-defects")

print("Path to dataset files:", fabric_path)
print("Path to dataset files:", frame_path)

!pip install torch --upgrade
!pip install torchvision --upgrade

# Commented out IPython magic to ensure Python compatibility.
# Import necessary libraries
import pandas as pd
import numpy as np
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import warnings
warnings.filterwarnings('ignore')

import torch                                 # PyTorch deep learning framework
import torch.nn as nn                        # Neural network module of PyTorch
import torch.optim as optim                  # Optimization algorithms
from torchvision import datasets, transforms # Tools for loading and transforming image data
from torch.utils.data import DataLoader      # Efficient data loading
import matplotlib.pyplot as plt              # For plotting and visualization. It is graphical library, to plot images
# special Jupyter notebook command to show plots inline instead of in a new window
# %matplotlib inline
from tqdm import tqdm                        # For progress bars during training

# Set plotting style
plt.style.use('seaborn-v0_8')
# %matplotlib inline

# Check if CUDA is available and set the device accordingly
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("Libraries imported successfully!")

"""# Task
Create a Convolutional Neural Network (CNN) classifier for the fabric stain dataset located at `'/root/.cache/kagglehub/datasets/priemshpathirana/fabric-stain-dataset/versions/1'`, including data preparation, model definition, training, and evaluation.

## Explore Fabric Dataset

### Subtask:
Examine the directory structure of the `fabric_path` to understand how the images are organized and to identify potential classes/labels. This might involve listing files and directories within `fabric_path`.

**Reasoning**:
The first step is to import the `os` module to interact with the file system and then list the contents of the `fabric_path` directory to examine its top-level structure, as specified in the instructions.
"""

import os

print(f"Contents of fabric_path: {fabric_path}")
for item in os.listdir(fabric_path):
    print(item)

"""**Reasoning**:
To understand how images are categorized and identify potential class names, I will list the contents of the 'images' subdirectory within `fabric_path`.


"""

images_path = os.path.join(fabric_path, 'images')
print(f"Contents of {images_path}:")
for item in os.listdir(images_path):
    print(item)

"""## Prepare Data Loaders

### Subtask:
Define image transformations (resizing, normalization, data augmentation), create datasets using `ImageFolder`, split them into training and validation sets, and then set up PyTorch `DataLoader`s.

**Reasoning**:
To prepare the data for training and validation, I will define the necessary image transformations, create an `ImageFolder` dataset from the specified path, split it into training and validation sets, and then set up `DataLoader`s for efficient batch processing, as detailed in the instructions.
"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
from torch.utils.data.sampler import WeightedRandomSampler # Import WeightedRandomSampler
import numpy as np

# 1. Define image transformations
# Mean and Standard Deviation for ImageNet pretrained models, common for transfer learning
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

# Training transformations with data augmentation
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),      # Resize images to 224x224
    transforms.RandomHorizontalFlip(),  # Randomly flip images horizontally for augmentation
    transforms.ToTensor(),              # Convert images to PyTorch tensors
    transforms.Normalize(mean, std)    # Normalize pixel values
])

# Validation transformations (no data augmentation)
val_transform = transforms.Compose([
    transforms.Resize((224, 224)),      # Resize images to 224x224
    transforms.ToTensor(),              # Convert images to PyTorch tensors
    transforms.Normalize(mean, std)    # Normalize pixel values
])

# 2. Create full dataset using ImageFolder
# The ImageFolder dataset will automatically infer classes from subdirectory names
full_dataset = datasets.ImageFolder(root=images_path, transform=train_transform)

# Determine the size of the dataset
dataset_size = len(full_dataset)

# 3. Determine sizes for training and validation sets (e.g., 80% train, 20% validation)
train_size = int(0.8 * dataset_size)
val_size = dataset_size - train_size

# 4. Split the full dataset into training and validation sets
train_dataset, val_dataset = random_split(full_dataset, [train_size, val_size])

# Apply validation transform to the validation subset
# Note: random_split returns subsets, but the transform applied to the ImageFolder
# is for the whole dataset. We need to create a new ImageFolder for validation
# with its specific transform, or apply transform directly. A more robust way:
val_full_dataset = datasets.ImageFolder(root=images_path, transform=val_transform)
val_indices = val_dataset.indices
val_dataset_transformed = torch.utils.data.Subset(val_full_dataset, val_indices)

# Calculate class weights for balanced sampling
train_targets = [train_dataset.dataset.targets[i] for i in train_dataset.indices]
class_counts = np.bincount(train_targets)
class_weights = 1. / class_counts
sample_weights = torch.tensor([class_weights[t] for t in train_targets])

# Create WeightedRandomSampler
sampler = WeightedRandomSampler(weights=sample_weights, num_samples=len(train_dataset), replacement=True)

# 5. Set up PyTorch DataLoader
batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, sampler=sampler, num_workers=2, shuffle=False)
val_loader = DataLoader(val_dataset_transformed, batch_size=batch_size, shuffle=False, num_workers=2)

# 6. Print information
print(f"Number of images in training set (after sampler setup): {len(train_dataset)}")
print(f"Number of images in validation set: {len(val_dataset_transformed)}")
print(f"Class names: {full_dataset.classes}")
print(f"Class to index mapping: {full_dataset.class_to_idx}")

print("Balanced data loaders and transformations successfully defined.")

"""## Define CNN Architecture

### Subtask:
Design a Convolutional Neural Network (CNN) model using PyTorch's `nn.Module`. This will involve defining convolutional layers, pooling layers, and fully connected layers for classification.

**Reasoning**:
To design the CNN architecture, I will define a class `CNNClassifier` inheriting from `nn.Module`, implement convolutional and fully connected layers in its `__init__` method, define the forward pass in the `forward` method, then instantiate the model, move it to the appropriate device, and print its summary.
"""

import torch.nn as nn

class CNNClassifier(nn.Module):
    def __init__(self, num_classes):
        super(CNNClassifier, self).__init__()
        # Convolutional layers
        self.features = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, padding=1), # Input: 3 channels (RGB), Output: 16 channels
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),    # Output size: 224/2 = 112

            nn.Conv2d(16, 32, kernel_size=3, padding=1), # Input: 16 channels, Output: 32 channels
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),    # Output size: 112/2 = 56

            nn.Conv2d(32, 64, kernel_size=3, padding=1), # Input: 32 channels, Output: 64 channels
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)     # Output size: 56/2 = 28
        )

        # Fully connected layers
        # Calculate input features for the first linear layer
        # (64 channels * 28 width * 28 height after convolutions and pooling)
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes) # Output: num_classes (2 for defect_free, stain)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# Instantiate the model
num_classes = len(full_dataset.classes)
model = CNNClassifier(num_classes=num_classes)

# Move the model to the appropriate device (GPU if available, else CPU)
model = model.to(device)

# Print the model architecture
print(model)
print(f"Model moved to device: {device}")

"""## Train CNN Model

### Subtask:
Implement the training loop for the CNN model. This includes defining the loss function (e.g., CrossEntropyLoss), an optimizer (e.g., Adam), and iterating through epochs to train the model on the prepared data.

**Reasoning**:
To train the CNN model, I will define the loss function and optimizer, set up data structures to store training and validation metrics, and then implement the full training loop including forward and backward passes, optimization, and evaluation for each epoch.
"""

import torch.optim as optim
from tqdm import tqdm

# 1. Define the loss function
criterion = nn.CrossEntropyLoss()

# 2. Define the optimizer
learning_rate = 0.001
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 3. Initialize empty lists to store metrics
train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []

# 4. Set the number of training epochs
num_epochs = 10

print("Starting model training with balanced data...")

# 5. Start a loop for the specified number of epochs
for epoch in range(num_epochs):
    # a. Set the model to training mode
    model.train()

    # b. Initialize running_loss and correct_predictions for the current epoch
    running_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    # c. Iterate through batches in the train_loader
    for inputs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1} Training (Balanced)"):
        # i. Move the input images and labels to the device
        inputs, labels = inputs.to(device), labels.to(device)

        # ii. Zero the gradients
        optimizer.zero_grad()

        # iii. Perform a forward pass
        outputs = model(inputs)

        # iv. Calculate the training loss
        loss = criterion(outputs, labels)

        # v. Perform a backward pass
        loss.backward()

        # vi. Update the model's weights
        optimizer.step()

        # vii. Update running_loss and correct_predictions for training statistics
        running_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total_samples += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

    # d. Calculate the average training loss and accuracy for the epoch and store them
    epoch_train_loss = running_loss / total_samples
    epoch_train_accuracy = correct_predictions / total_samples
    train_losses.append(epoch_train_loss)
    train_accuracies.append(epoch_train_accuracy)

    # e. Set the model to evaluation mode
    model.eval()

    # f. Disable gradient calculations for validation
    with torch.no_grad():
        # g. Initialize val_running_loss and val_correct_predictions for the current epoch
        val_running_loss = 0.0
        val_correct_predictions = 0
        val_total_samples = 0

        # h. Iterate through batches in the val_loader
        for inputs, labels in tqdm(val_loader, desc=f"Epoch {epoch+1} Validation"):
            # i. Move the input images and labels to the device
            inputs, labels = inputs.to(device), labels.to(device)

            # ii. Perform a forward pass
            outputs = model(inputs)

            # iii. Calculate the validation loss
            loss = criterion(outputs, labels)

            # iv. Update val_running_loss and val_correct_predictions for validation statistics
            val_running_loss += loss.item() * inputs.size(0)
            _, predicted = torch.max(outputs.data, 1)
            val_total_samples += labels.size(0)
            val_correct_predictions += (predicted == labels).sum().item()

    # i. Calculate the average validation loss and accuracy for the epoch and store them
    epoch_val_loss = val_running_loss / val_total_samples
    epoch_val_accuracy = val_correct_predictions / val_total_samples
    val_losses.append(epoch_val_loss)
    val_accuracies.append(epoch_val_accuracy)

    # j. Print the training and validation loss and accuracy for the current epoch
    print(f"Epoch {epoch+1}/{num_epochs} - "
          f"Train Loss: {epoch_train_loss:.4f}, Train Acc: {epoch_train_accuracy:.4f} | "
          f"Val Loss: {epoch_val_loss:.4f}, Val Acc: {epoch_val_accuracy:.4f}")

print("Model training with balanced data finished.")

"""**Reasoning**:
The training of the CNN model is complete. The next logical step is to evaluate its performance using the collected metrics (loss and accuracy) and visualize them to understand the model's learning process. I will plot the training and validation loss and accuracy, calculate the final accuracy on the validation set, and print the classification report and confusion matrix.


"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# 1. Plot training and validation loss
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(train_losses, label='Training Loss')
plt.plot(val_losses, label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# 2. Plot training and validation accuracy
plt.subplot(1, 2, 2)
plt.plot(train_accuracies, label='Training Accuracy')
plt.plot(val_accuracies, label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# 3. Calculate final accuracy on the validation set and print classification report and confusion matrix
model.eval()  # Set the model to evaluation mode
all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in val_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

final_accuracy = accuracy_score(all_labels, all_preds)
print(f"\nFinal Validation Accuracy: {final_accuracy:.4f}")

# Get class names from the dataset
class_names = full_dataset.classes

print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=class_names))

print("\nConfusion Matrix:")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Visual evaluation of sample predictions
model.eval()
dataiter = iter(val_loader)
images, labels = next(dataiter)
images, labels = images.to(device), labels.to(device)

with torch.no_grad():
    outputs = model(images)
_, predicted = torch.max(outputs, 1)

def denormalize_image(image_tensor, mean, std):
    image_copy = image_tensor.clone().cpu()
    for t, m, s in zip(image_copy, mean, std):
        t.mul_(s).add_(m)
    return np.clip(image_copy.numpy().transpose((1, 2, 0)), 0, 1)

fig = plt.figure(figsize=(10, 10))
fig.suptitle('Sample Predictions from Validation Set', fontsize=16)

num_images_to_show = min(len(images), 16)

for idx in range(num_images_to_show):
    ax = fig.add_subplot(4, 4, idx + 1, xticks=[], yticks=[])
    img = denormalize_image(images[idx], mean, std)
    ax.imshow(img)
    true_label = full_dataset.classes[labels[idx].item()]
    predicted_label = full_dataset.classes[predicted[idx].item()]
    color = 'green' if true_label == predicted_label else 'red'
    ax.set_title(f'True: {true_label}\nPred: {predicted_label}', color=color, fontsize=8)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

print("Visual evaluation of model predictions complete.")

"""## Final Task

### Subtask:
Summarize the process of creating the CNN classifier, including the dataset used, the model architecture, and its performance.

## Summary:

## Q&A

The process of creating the CNN classifier for the fabric stain dataset involved several key steps:

1.  **Dataset Exploration**: The dataset, located at `/root/.cache/kagglehub/datasets/priemshpathirana/fabric-stain-dataset/versions/1`, was explored. It contains an `images` directory with two subdirectories: `defect_free` and `stain`, which served as the two class labels for the classification task.
2.  **Data Preparation**:
    *   **Image Transformations**: Images were resized to 224x224 pixels. Training data underwent random horizontal flipping for augmentation, while both training and validation sets were converted to PyTorch tensors and normalized using ImageNet's mean and standard deviation.
    *   **Dataset and Dataloaders**: `datasets.ImageFolder` was used to load images, which were then split into an 80% training set (372 images) and a 20% validation set (94 images). PyTorch `DataLoader`s were created with a batch size of 32 for both sets.
3.  **Model Definition**: A custom `CNNClassifier` was defined using `torch.nn.Module`.
    *   **Feature Extractor**: It consists of three convolutional blocks, each with `nn.Conv2d`, `nn.ReLU`, and `nn.MaxPool2d` layers. The channel progression was from 3 (RGB) to 16, then 32, and finally 64 channels.
    *   **Classifier Head**: The features were flattened and passed through two fully connected layers (`nn.Linear` with ReLU activation) before the final output layer, which had 2 neurons corresponding to the `defect_free` and `stain` classes.
4.  **Model Training**: The model was trained for 10 epochs using `nn.CrossEntropyLoss` as the criterion and `optim.Adam` with a learning rate of 0.001 as the optimizer.
5.  **Model Evaluation**: After training, the model's performance was evaluated on the validation set using accuracy, a classification report, and a confusion matrix.

## Data Analysis Key Findings

*   The dataset is comprised of images categorized into two classes: `defect_free` and `stain`.
*   The training set contained 372 images, and the validation set contained 94 images.
*   The custom CNN model architecture consisted of three convolutional layers, followed by a flatten layer and two fully connected layers, outputting 2 classes.
*   The model achieved a final validation accuracy of **86.17%** after 10 epochs.
*   The classification report revealed a significant disparity in performance between classes:
    *   The `stain` class showed strong performance with a precision of **0.89**, recall of **0.96**, and an f1-score of **0.93**.
    *   Conversely, the `defect_free` class demonstrated a precision, recall, and f1-score of **0.00**, indicating that the model failed to correctly classify any instances of this class.
*   The confusion matrix visually confirmed that all `defect_free` samples were misclassified, while the `stain` class was largely correctly identified.

## Insights or Next Steps

*   The model exhibits a strong bias towards classifying images as 'stain', completely failing to identify 'defect\_free' images. This could be due to a severe class imbalance not apparent in the provided summary, or inherent difficulty in distinguishing between the classes. Re-examining the class distribution and sample characteristics for 'defect\_free' is crucial.
*   To address the poor performance on the `defect_free` class, consider strategies such as oversampling the minority class, undersampling the majority class, using weighted loss functions, or employing more advanced data augmentation techniques for the `defect_free` class. Further investigation into the quality and representativeness of `defect_free` images is also recommended.

Frame Path
"""

# Commented out IPython magic to ensure Python compatibility.
# Install required libraries
# The %pip command installs packages in Jupyter notebooks
# %pip install tensorflow tensorflow-hub tensorflow-datasets matplotlib

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
from io import BytesIO

print("TensorFlow version:", tf.__version__)
print("TensorFlow Hub version:", hub.__version__)

"""# Task
Perform object detection on a sampled subset of the wood surface defects dataset located at `'/root/.cache/kagglehub/datasets/nomihsa965/large-scale-image-dataset-of-wood-surface-defects/versions/1'`, using a pre-trained SSD MobileNet V2 model from TensorFlow Hub to detect defects, and visualize the results.

## Prepare Data Paths and Mappings

### Subtask:
Confirm the directory structure within `frame_path` for images and annotations. Create a list of image and annotation file paths and establish a clear mapping between them to ensure correct pairing.

**Reasoning**:
To begin, I will print the `frame_path` and list its contents to understand the directory structure and identify the subdirectories containing images and annotations, as specified in the instructions.
"""

import os

# 2. Print the frame_path
print(f"Base frame_path: {frame_path}")

# 3. List the contents of frame_path
print("Contents of frame_path:")
for item in os.listdir(frame_path):
    print(item)

"""**Reasoning**:
Based on the identified subdirectories, I will construct the full paths to the actual image and annotation directories, then generate lists of all image and annotation file paths, and finally create a mapping between them.


"""

import os

# Construct the full paths to the images and annotations directories
images_dir_base = 'Images - 1'
annotations_dir_base = 'Bounding Boxes - YOLO Format - 1'

actual_images_dir = os.path.join(frame_path, images_dir_base, images_dir_base)
actual_annotations_dir = os.path.join(frame_path, annotations_dir_base, annotations_dir_base)

print(f"Actual images directory: {actual_images_dir}")
print(f"Actual annotations directory: {actual_annotations_dir}")

# Create a list of all image file paths
image_paths = []
for root, _, files in os.walk(actual_images_dir):
    for file in files:
        if file.endswith('.jpg') or file.endswith('.jpeg') or file.endswith('.png'):
            image_paths.append(os.path.join(root, file))

# Create a list of all annotation file paths
annotation_paths = []
for root, _, files in os.walk(actual_annotations_dir):
    for file in files:
        if file.endswith('.txt'):
            annotation_paths.append(os.path.join(root, file))

print(f"Found {len(image_paths)} image files.")
print(f"Found {len(annotation_paths)} annotation files.")

# Create a mapping from image filename (without extension) to its full path and annotation path
image_map = {os.path.splitext(os.path.basename(p))[0]: p for p in image_paths}
annotation_map = {os.path.splitext(os.path.basename(p))[0]: p for p in annotation_paths}

# Create paired lists of image and annotation paths for files that have both
pairable_files = []
for img_filename_base, img_path in image_map.items():
    if img_filename_base in annotation_map:
        pairable_files.append((img_path, annotation_map[img_filename_base]))

print(f"Found {len(pairable_files)} paired image and annotation files.")

# Display a few example pairs
print("\nExample paired files:")
for i, (img_p, ann_p) in enumerate(pairable_files[:5]):
    print(f"Image: {os.path.basename(img_p)}, Annotation: {os.path.basename(ann_p)}")

"""## Sample a Subset of the Dataset

### Subtask:
Randomly sample a fixed number of image-annotation pairs from the full dataset to limit the amount of data used for processing and model evaluation. This will help in faster experimentation.

**Reasoning**:
To create a manageable subset for experimentation, I will first import the `random` module. Then, I'll define `sample_size` as 400 and use `random.sample` to select that many image-annotation pairs from the `pairable_files` list. Finally, I will separate these sampled pairs into two distinct lists: `sampled_image_paths` and `sampled_annotation_paths`, and print their lengths to verify the sampling.
"""

import random

# 1. Define sample_size
sample_size = 400

# 2. Randomly select sample_size pairs from pairable_files
sampled_pairs = random.sample(pairable_files, min(sample_size, len(pairable_files)))

# 3. Separate the sampled pairs into image and annotation paths
sampled_image_paths = [pair[0] for pair in sampled_pairs]
sampled_annotation_paths = [pair[1] for pair in sampled_pairs]

# 4. Print the number of sampled files
print(f"Number of sampled image files: {len(sampled_image_paths)}")
print(f"Number of sampled annotation files: {len(sampled_annotation_paths)}")
print("Sampled image and annotation paths created successfully.")

"""**Reasoning**:
Now that a sampled subset of image and annotation paths has been created, the next step is to define a function to parse the YOLO format annotations associated with these images. This function will convert the raw YOLO bounding box data (class_id, center_x, center_y, width, height, all normalized) into a more usable format, making it easier to integrate with the object detection model.


"""

def parse_yolo_annotation(annotation_path, image_width, image_height):
    """
    Parses a YOLO format annotation file and returns a list of dictionaries,
    each representing a bounding box with class_id, center_x, center_y, width, and height.
    """
    bboxes = []
    try:
        with open(annotation_path, 'r') as f:
            for line in f:
                parts = list(map(float, line.strip().split()))
                if len(parts) == 5:
                    class_id, center_x, center_y, width, height = parts
                    bboxes.append({
                        'class_id': int(class_id),
                        'center_x': center_x,
                        'center_y': center_y,
                        'width': width,
                        'height': height
                    })
    except FileNotFoundError:
        print(f"Warning: Annotation file not found: {annotation_path}")
    except Exception as e:
        print(f"Error parsing annotation file {annotation_path}: {e}")
    return bboxes

print("YOLO annotation parsing function defined.")

"""**Reasoning**:
Now that the YOLO annotation parsing function is defined, I need to create a TensorFlow function that can load an image, read its dimensions, parse its corresponding YOLO annotation, convert the normalized YOLO bounding box coordinates to absolute coordinates, and return the processed image and bounding boxes. This function will be crucial for creating a `tf.data.Dataset`.


"""

import tensorflow as tf
import numpy as np

# Define image dimensions for the model
IMG_WIDTH = 320
IMG_HEIGHT = 320

def load_and_preprocess_image_and_boxes(image_path, annotation_path):
    # Load the image
    img = tf.io.read_file(image_path)
    img = tf.image.decode_jpeg(img, channels=3)

    # Get original image dimensions for bounding box conversion
    original_shape = tf.shape(img)
    original_height = tf.cast(original_shape[0], tf.float32)
    original_width = tf.cast(original_shape[1], tf.float32)

    # Resize image to model input size
    img = tf.image.resize(img, [IMG_HEIGHT, IMG_WIDTH])
    img = img / 255.0  # Normalize pixel values to [0, 1]

    # Read annotation file
    annotation_raw = tf.io.read_file(annotation_path)
    # Decode the raw annotation string into individual lines
    lines = tf.strings.split(annotation_raw, sep='\n')

    # Filter out empty lines
    valid_lines = tf.boolean_mask(lines, tf.strings.length(lines) > 0)

    def parse_line(line):
        parts = tf.strings.split(line, sep=' ')
        parts = tf.strings.to_number(parts, out_type=tf.float32)

        class_id = tf.cast(parts[0], tf.int32)
        center_x_norm, center_y_norm, width_norm, height_norm = parts[1], parts[2], parts[3], parts[4]

        # Convert YOLO normalized coordinates to absolute coordinates (ymin, xmin, ymax, xmax)
        xmin = (center_x_norm - width_norm / 2) * original_width
        ymin = (center_y_norm - height_norm / 2) * original_height
        xmax = (center_x_norm + width_norm / 2) * original_width
        ymax = (center_y_norm + height_norm / 2) * original_height

        # Bounding box format: [class_id, ymin, xmin, ymax, xmax]
        # We need normalized coordinates for the model, relative to the resized image
        # Convert to normalized coordinates relative to resized image (0-1 range)
        # Note: Some models expect boxes in [ymin, xmin, ymax, xmax] format
        # and normalized to [0, 1]. Here, we are converting back to normalized
        # coordinates for the resized image. The model might handle the scaling internally
        # or expect specific format. For SSD, usually it expects normalized [ymin, xmin, ymax, xmax].

        # Scale bounding box coordinates to the resized image dimensions [0,1]
        xmin_scaled = xmin / original_width
        ymin_scaled = ymin / original_height
        xmax_scaled = xmax / original_width
        ymax_scaled = ymax / original_height

        # Ensure coordinates are within [0, 1]
        xmin_scaled = tf.clip_by_value(xmin_scaled, 0.0, 1.0)
        ymin_scaled = tf.clip_by_value(ymin_scaled, 0.0, 1.0)
        xmax_scaled = tf.clip_by_value(xmax_scaled, 0.0, 1.0)
        ymax_scaled = tf.clip_by_value(ymax_scaled, 0.0, 1.0)

        # The output format for SSD MobileNet typically expects:
        # [ymin, xmin, ymax, xmax] for the box and then the class_id
        # Sticking to the request's output format, let's keep [class_id, ymin, xmin, ymax, xmax]
        # but for object detection models like SSD, it's often boxes first then classes.
        # Let's return boxes as [ymin, xmin, ymax, xmax] and class_ids separately
        return tf.stack([ymin_scaled, xmin_scaled, ymax_scaled, xmax_scaled]), class_id

    # Map the parsing function over each valid line
    if tf.equal(tf.shape(valid_lines)[0], 0):
        # Handle case where there are no bounding boxes in the annotation file
        empty_boxes = tf.zeros((0, 4), dtype=tf.float32)
        empty_classes = tf.zeros((0,), dtype=tf.int32)
        return img, empty_boxes, empty_classes

    boxes, classes = tf.map_fn(
        parse_line,
        valid_lines,
        fn_output_signature=(tf.TensorSpec(shape=(4,), dtype=tf.float32), tf.TensorSpec(shape=(), dtype=tf.int32)),
        parallel_iterations=10 # Adjust as needed
    )

    return img, boxes, classes

print("TensorFlow function `load_and_preprocess_image_and_boxes` defined.")

"""## Construct TensorFlow Dataset for Object Detection

### Subtask:
Create a `tf.data.Dataset` using the sampled image and annotation paths. Apply the data loading and preprocessing functions to each element of the dataset. Batch the dataset for efficient processing, ensuring that bounding box tensors are padded correctly to handle varying numbers of detections per image.

**Reasoning**:
To construct the `tf.data.Dataset` for object detection, I will define batch size and class names, create a dataset from the sampled image and annotation paths, apply the preprocessing function using `map` with parallel calls, cache and prefetch the dataset for performance, and finally batch the dataset using `padded_batch` with appropriate shapes and padding values for images, bounding boxes, and class IDs.
"""

BATCH_SIZE = 16 # Define the batch size
CLASS_NAMES = ['wood_defect_type_0', 'wood_defect_type_1'] # Define class names for defects

# 2. Create a tf.data.Dataset from the sampled paths
dataset = tf.data.Dataset.from_tensor_slices((sampled_image_paths, sampled_annotation_paths))

# 3. Map the preprocessing function to the dataset
dataset = dataset.map(load_and_preprocess_image_and_boxes, num_parallel_calls=tf.data.AUTOTUNE)

# 4. Apply cache() and prefetch() for performance
dataset = dataset.cache().prefetch(tf.data.AUTOTUNE)

# 5. Use padded_batch() to handle variable numbers of bounding boxes per image
padded_shapes = (
    tf.TensorShape([IMG_HEIGHT, IMG_WIDTH, 3]), # Image shape
    tf.TensorShape([None, 4]),                  # Bounding boxes (variable number of boxes, 4 coordinates per box)
    tf.TensorShape([None])                       # Class IDs (variable number of classes)
)
padding_values = (
    tf.constant(0.0, dtype=tf.float32),           # Padding for image pixels
    tf.constant(0.0, dtype=tf.float32),           # Padding for bounding box coordinates
    tf.constant(-1, dtype=tf.int32)              # Padding for class IDs
)

batched_dataset = dataset.padded_batch(BATCH_SIZE, padded_shapes=padded_shapes, padding_values=padding_values)

print(f"TensorFlow Dataset created with {len(sampled_image_paths)} samples.")
print(f"Batch size: {BATCH_SIZE}")
print(f"Class names: {CLASS_NAMES}")
print("Dataset prepared successfully for object detection.")

"""## Load Pre-trained SSD MobileNet Model

### Subtask:
Load the pre-trained SSD MobileNet V2 model from TensorFlow Hub using the provided `TF_MODEL_URL`.

**Reasoning**:
To load the pre-trained SSD MobileNet V2 model, I will define its TensorFlow Hub URL and then use `hub.load()` to load the model into a `detector` variable, finally confirming the successful load.
"""

import tensorflow_hub as hub

# 1. Define the TF_MODEL_URL variable
TF_MODEL_URL = 'https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2'

# 2. Load the pre-trained model
detector = hub.load(TF_MODEL_URL)

# 3. Print a confirmation message
print(f"Pre-trained SSD MobileNet V2 model loaded successfully from {TF_MODEL_URL}")

"""## Perform Inference and Visualize Detections

### Subtask:
Take a sample batch of images from the prepared dataset. Run inference using the loaded SSD MobileNet model to obtain predictions (detection boxes, scores, and class labels). Implement a visualization function to draw these predicted bounding boxes and class labels onto the original images using `matplotlib.patches`. Display these visualized images to show the detected defects.

**Reasoning**:
To perform inference and visualize detections, I will first extract a sample batch from the `batched_dataset`, prepare the images for the detector model, run the inference, and then extract the detection results. After that, I will define the COCO dataset labels, and create a `visualize_detections` function to draw the predicted bounding boxes and class labels onto the images, and then loop through each image in the batch to display the detections.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Get a single batch of preprocessed images, ground truth bounding boxes, and ground truth class IDs
for images, gt_boxes, gt_classes in batched_dataset.take(1):
    break # Get the first batch

print(f"Shape of images in batch: {images.shape}")
print(f"Shape of ground truth boxes in batch: {gt_boxes.shape}")
print(f"Shape of ground truth classes in batch: {gt_classes.shape}")

# 5. Define COCO dataset labels (SSD MobileNet V2 is trained on COCO)
# The model outputs 1-indexed classes, so we need to adjust for 0-indexed list.
# The first element is often a placeholder for background or is unused.
# This list is simplified as we only care about 'defect' for visualization purposes,
# but a full COCO labels list would be much longer.
# For this dataset, let's map generic COCO classes to our understanding of 'defects'.
# Note: SSD MobileNet V2 typically outputs COCO classes, not custom classes from the wood dataset.
# We will use generic 'object' for visualization or try to map if specific classes are known from COCO.
# Let's assume for simplicity, any detection from the pre-trained model implies a 'defect'.
# A proper mapping requires knowing which COCO classes correspond to wood defects.
# For demonstration, we'll use a simplified mapping or just print the COCO class ID.

# Standard COCO classes (simplified for common objects and filling for indexing)
coco_labels = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
    'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'N/A', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'N/A', 'backpack', 'umbrella', 'N/A',
    'N/A', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
    'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
    'bottle', 'N/A', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana',
    'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
    'cake', 'chair', 'couch', 'potted plant', 'bed', 'N/A', 'dining table', 'N/A',
    'N/A', 'toilet', 'N/A', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
    'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'N/A', 'book', 'clock',
    'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]

# 6. Define the visualization function
def visualize_detections(image_np, boxes, scores, classes, category_index, threshold=0.5):
    fig, ax = plt.subplots(1, figsize=(10, 10))
    ax.imshow(image_np)
    ax.set_title("Object Detections")
    ax.axis('off')

    img_height, img_width, _ = image_np.shape

    for i in range(len(scores)):
        if scores[i] > threshold:
            # Boxes are in normalized [ymin, xmin, ymax, xmax] format
            ymin, xmin, ymax, xmax = boxes[i]

            # Scale coordinates to original image dimensions
            x = xmin * img_width
            y = ymin * img_height
            width = (xmax - xmin) * img_width
            height = (ymax - ymin) * img_height

            # Draw rectangle
            rect = patches.Rectangle((x, y), width, height, linewidth=2, edgecolor='r', facecolor='none')
            ax.add_patch(rect)

            # Add text label (class name and score)
            # The model's classes are 1-indexed, so we subtract 1 for python list indexing
            class_name = category_index[classes[i]] if classes[i] < len(category_index) else f'Class {classes[i]}'
            label_text = f'{class_name}: {scores[i]:.2f}'
            ax.text(x, y - 10, label_text, color='white', fontsize=10, bbox=dict(facecolor='red', alpha=0.7))
    plt.show()

print("Visualization function `visualize_detections` defined.")

# 7. Loop through each image and its corresponding detections in the batch
print("Displaying sample detections:")
for i in range(images.shape[0]):
    if i >= 4: # Limit to 4 images for brevity
        break

    print(f"\nProcessing image {i+1}/{images.shape[0]}")

    # Prepare single image for detection
    # Convert images from float32 [0,1] to uint8 [0,255] and add batch dimension
    image_for_detection = tf.expand_dims(tf.cast(images[i] * 255, tf.uint8), axis=0)

    # 3. Run inference on the single image
    result = detector(image_for_detection)

    # 4. Extract detection results
    # Convert results to NumPy arrays for easier manipulation. Take the first element as batch_size is 1.
    det_boxes = result['detection_boxes'][0].numpy()
    det_scores = result['detection_scores'][0].numpy()
    det_classes = result['detection_classes'][0].numpy().astype(np.int32)
    # num_detections is also a tensor with one element, extract its value
    num_detections_single_image = int(result['num_detections'][0].numpy())

    # Get the image in NumPy format for visualization
    image_np = images[i].numpy() # This image is already normalized [0,1] for imshow

    # The SSD MobileNet model outputs classes that are 1-indexed.
    # So, we pass the raw classes and handle the indexing inside visualize_detections.
    visualize_detections(image_np, det_boxes[:num_detections_single_image], det_scores[:num_detections_single_image], det_classes[:num_detections_single_image], coco_labels, threshold=0.3)

print("Inference and visualization complete.")

"""**Reasoning**:
The error message indicates that the object detection model expects input images to be of type `tf.uint8` and have a batch dimension of 1 (i.e., `(1, None, None, 3)`), but it received `tf.float32` images with a batch size of 16. To fix this, I need to convert each image to `tf.uint8`, normalize it to the 0-255 range, and then process them one by one by adding a batch dimension before passing them to the detector.


"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Get a single batch of preprocessed images, ground truth bounding boxes, and ground truth class IDs
for images, gt_boxes, gt_classes in batched_dataset.take(1):
    break # Get the first batch

print(f"Shape of images in batch: {images.shape}")
print(f"Shape of ground truth boxes in batch: {gt_boxes.shape}")
print(f"Shape of ground truth classes in batch: {gt_classes.shape}")

# 5. Define COCO dataset labels (SSD MobileNet V2 is trained on COCO)
# The model outputs 1-indexed classes, so we need to adjust for 0-indexed list.
# The first element is often a placeholder for background or is unused.
# This list is simplified as we only care about 'defect' for visualization purposes,
# but a full COCO labels list would be much longer.
# For this dataset, let's map generic COCO classes to our understanding of 'defects'.
# Note: SSD MobileNet V2 typically outputs COCO classes, not custom classes from the wood dataset.
# We will use generic 'object' for visualization or try to map if specific classes are known from COCO.
# Let's assume for simplicity, any detection from the pre-trained model implies a 'defect'.
# A proper mapping requires knowing which COCO classes correspond to wood defects.
# For demonstration, we'll use a simplified mapping or just print the COCO class ID.

# Standard COCO classes (simplified for common objects and filling for indexing)
coco_labels = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
    'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'N/A', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'N/A', 'backpack', 'umbrella', 'N/A',
    'N/A', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
    'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
    'bottle', 'N/A', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana',
    'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
    'cake', 'chair', 'couch', 'potted plant', 'bed', 'N/A', 'dining table', 'N/A',
    'N/A', 'toilet', 'N/A', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
    'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'N/A', 'book', 'clock',
    'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]

# 6. Define the visualization function
def visualize_detections(image_np, boxes, scores, classes, category_index, threshold=0.5):
    fig, ax = plt.subplots(1, figsize=(10, 10))
    ax.imshow(image_np)
    ax.set_title("Object Detections")
    ax.axis('off')

    img_height, img_width, _ = image_np.shape

    for i in range(len(scores)):
        if scores[i] > threshold:
            # Boxes are in normalized [ymin, xmin, ymax, xmax] format
            ymin, xmin, ymax, xmax = boxes[i]

            # Scale coordinates to original image dimensions
            x = xmin * img_width
            y = ymin * img_height
            width = (xmax - xmin) * img_width
            height = (ymax - ymin) * img_height

            # Draw rectangle
            rect = patches.Rectangle((x, y), width, height, linewidth=2, edgecolor='r', facecolor='none')
            ax.add_patch(rect)

            # Add text label (class name and score)
            # The model's classes are 1-indexed, so we subtract 1 for python list indexing
            class_name = category_index[classes[i]] if classes[i] < len(category_index) else f'Class {classes[i]}'
            label_text = f'{class_name}: {scores[i]:.2f}'
            ax.text(x, y - 10, label_text, color='white', fontsize=10, bbox=dict(facecolor='red', alpha=0.7))
    plt.show()

print("Visualization function `visualize_detections` defined.")

# 7. Loop through each image and its corresponding detections in the batch
print("Displaying sample detections:")
for i in range(images.shape[0]):
    if i >= 4: # Limit to 4 images for brevity
        break

    print(f"\nProcessing image {i+1}/{images.shape[0]}")

    # Prepare single image for detection
    # Convert images from float32 [0,1] to uint8 [0,255] and add batch dimension
    image_for_detection = tf.expand_dims(tf.cast(images[i] * 255, tf.uint8), axis=0)

    # 3. Run inference on the single image
    result = detector(image_for_detection)

    # 4. Extract detection results
    # Convert results to NumPy arrays for easier manipulation. Take the first element as batch_size is 1.
    det_boxes = result['detection_boxes'][0].numpy()
    det_scores = result['detection_scores'][0].numpy()
    det_classes = result['detection_classes'][0].numpy().astype(np.int32)
    # num_detections is also a tensor with one element, extract its value
    num_detections_single_image = int(result['num_detections'][0].numpy())

    # Get the image in NumPy format for visualization
    image_np = images[i].numpy() # This image is already normalized [0,1] for imshow

    # The SSD MobileNet model outputs classes that are 1-indexed.
    # So, we pass the raw classes and handle the indexing inside visualize_detections.
    visualize_detections(image_np, det_boxes[:num_detections_single_image], det_scores[:num_detections_single_image], det_classes[:num_detections_single_image], coco_labels, threshold=0.3)

print("Inference and visualization complete.")

"""## Final Task

### Subtask:
Summarize the process, the detected defects, and the performance of the object detection model.

## Summary:

### Data Analysis Key Findings

*   **Data Preparation and Pairing**: A total of 4000 image files and 4000 annotation files were successfully identified and paired from the dataset, ensuring a one-to-one correspondence between images and their YOLO-formatted bounding box annotations.
*   **Dataset Sampling**: A subset of 400 image-annotation pairs was randomly sampled from the full dataset to facilitate faster experimentation.
*   **TensorFlow Dataset Creation**: A `tf.data.Dataset` was successfully constructed using the 400 sampled pairs. It incorporated image preprocessing (resizing to 320x320 and normalization), caching, prefetching, and padded batching with a `BATCH_SIZE` of 16 to handle varying numbers of bounding boxes per image.
*   **Model Loading**: The pre-trained SSD MobileNet V2 model was successfully loaded from TensorFlow Hub using the URL `https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2`.
*   **Inference and Visualization**:
    *   Initial attempts to run inference on a batch of preprocessed images resulted in a `TypeError` due to a mismatch in input data type and shape. The model expected `tf.uint8` images with a batch size of 1, whereas the input was `tf.float32` with a batch size of 16.
    *   The issue was resolved by processing images individually, converting `tf.float32` images (0-1 range) to `tf.uint8` (0-255 range), and adding a batch dimension of 1 for each image before passing it to the detector.
    *   The corrected inference successfully detected objects, and a custom visualization function plotted the detected bounding boxes, scores, and COCO class labels on sample images. The visualization demonstrated the model's ability to identify objects within the wood surface defect images, albeit using generic COCO classes.

### Insights or Next Steps

*   The current approach uses an SSD MobileNet V2 model pre-trained on the COCO dataset, which is designed for general object detection. While it successfully identifies objects, these detections might not directly correspond to specific "wood defect types" as intended by the dataset annotations. A crucial next step would be to fine-tune this model or train a new model on the wood surface defects dataset to recognize the specific defect classes (e.g., 'wood\_defect\_type\_0', 'wood\_defect\_type\_1').
*   To evaluate the model's performance on wood defects accurately, a quantitative evaluation (e.g., using metrics like Mean Average Precision (mAP)) is necessary. This would involve comparing the model's predictions against the ground truth annotations for the sampled dataset, potentially requiring a custom metric given the difference in class labels between the pre-trained model and the wood defect dataset.
"""